/**
 * @fileoverview gRPC-Web generated client stub for cities
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.13.0
// source: city/city_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var city_city_message_pb = require('../city/city_message_pb.js')
const proto = {};
proto.cities = require('./city_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cities.CitiesServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cities.CitiesServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cities.City,
 *   !proto.cities.City>}
 */
const methodDescriptor_CitiesService_GetCity = new grpc.web.MethodDescriptor(
  '/cities.CitiesService/GetCity',
  grpc.web.MethodType.UNARY,
  city_city_message_pb.City,
  city_city_message_pb.City,
  /**
   * @param {!proto.cities.City} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  city_city_message_pb.City.deserializeBinary
);


/**
 * @param {!proto.cities.City} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cities.City)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cities.City>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cities.CitiesServiceClient.prototype.getCity =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cities.CitiesService/GetCity',
      request,
      metadata || {},
      methodDescriptor_CitiesService_GetCity,
      callback);
};


/**
 * @param {!proto.cities.City} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cities.City>}
 *     Promise that resolves to the response
 */
proto.cities.CitiesServicePromiseClient.prototype.getCity =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cities.CitiesService/GetCity',
      request,
      metadata || {},
      methodDescriptor_CitiesService_GetCity);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cities.EmptyMessage,
 *   !proto.cities.CitiesStream>}
 */
const methodDescriptor_CitiesService_GetCities = new grpc.web.MethodDescriptor(
  '/cities.CitiesService/GetCities',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.cities.EmptyMessage,
  proto.cities.CitiesStream,
  /**
   * @param {!proto.cities.EmptyMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cities.CitiesStream.deserializeBinary
);


/**
 * @param {!proto.cities.EmptyMessage} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.cities.CitiesStream>}
 *     The XHR Node Readable Stream
 */
proto.cities.CitiesServiceClient.prototype.getCities =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/cities.CitiesService/GetCities',
      request,
      metadata || {},
      methodDescriptor_CitiesService_GetCities);
};


/**
 * @param {!proto.cities.EmptyMessage} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.cities.CitiesStream>}
 *     The XHR Node Readable Stream
 */
proto.cities.CitiesServicePromiseClient.prototype.getCities =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/cities.CitiesService/GetCities',
      request,
      metadata || {},
      methodDescriptor_CitiesService_GetCities);
};


module.exports = proto.cities;

